# Generated by Django 6.0.2 on 2026-02-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_show_user_alter_show_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
