apiVersion: v1
kind: Service
metadata:
  name: watchlist-service
spec:
  type: NodePort
  selector:
    app: watchlist
  ports:
    - port: 80
      targetPort: 8000


# This service exposes the watchlist application on a NodePort, which allows access to the application from outside the Kubernetes cluster.